/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005-2015
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

#ifndef _VMBOARD_SDK_H
#define _VMBOARD_SDK_H

#ifdef __cplusplus
extern "C" {
#endif

#include "vmtype.h"

/* pin mux mode */
typedef enum
{
    VM_DCL_PIN_MODE_GPIO = 1,  /* gpio mode */
    VM_DCL_PIN_MODE_ADC,       /* adc mode */
    VM_DCL_PIN_MODE_PWM,       /* pwm mode */
    VM_DCL_PIN_MODE_UART,      /* uart mode */
    VM_DCL_PIN_MODE_EINT,      /* eint mode */
    VM_DCL_PIN_MODE_SPI,       /* spi mode */
    VM_DCL_PIN_MODE_I2C,       /* i2c mode */
    VM_DCL_PIN_MODE_SDIO,      /* sdio mode */
    VM_DCL_PIN_MODE_DBI_C,     /* dbi mode */
} VM_DCL_PIN_MODE;

#if defined(__HDK_LINKIT_ONE_V1__)
#define VM_PIN_D0  10     /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_UART */
#define VM_PIN_D1  11     /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_UART */
#define VM_PIN_D2  46     /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_EINT */
#define VM_PIN_D3  13     /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_EINT / VM_DCL_PIN_MODE_PWM */
#define VM_PIN_D4  40     /* Pin mux, VM_DCL_PIN_MODE_GPIO */
#define VM_PIN_D5  3      /* Pin mux, VM_DCL_PIN_MODE_GPIO */
#define VM_PIN_D6  25     /* Pin mux, VM_DCL_PIN_MODE_GPIO */
#define VM_PIN_D7  50     /* Pin mux, VM_DCL_PIN_MODE_GPIO */
#define VM_PIN_D8  48     /* Pin mux, VM_DCL_PIN_MODE_GPIO */
#define VM_PIN_D9  19     /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_PWM */
#define VM_PIN_D10 26     /* Pin mux, VM_DCL_PIN_MODE_GPIO */
#define VM_PIN_D11 28     /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_SPI / VM_DCL_PIN_MODE_SDIO */
#define VM_PIN_D12 29     /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_SPI / VM_DCL_PIN_MODE_SDIO */
#define VM_PIN_D13 27     /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_SPI / VM_DCL_PIN_MODE_SDIO */
#define VM_PIN_D14 0      /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_ADC */
#define VM_PIN_D15 1      /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_ADC */
#define VM_PIN_D16 2      /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_ADC */
#define VM_PIN_D18 44     /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_I2C */
#define VM_PIN_D19 43     /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_I2C */
#define VM_PIN_A0 0       /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_ADC */
#define VM_PIN_A1 1       /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_ADC */
#define VM_PIN_A2 2       /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_ADC */
#define VM_PIN_SDA 44     /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_I2C */
#define VM_PIN_SCL 43     /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_I2C */
#define VM_PIN_RX  10     /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_UART */
#define VM_PIN_TX  11     /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_UART */
#elif defined(__HDK_LINKIT_ASSIST_2502__)
#define VM_PIN_P0 13      /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_PWM / VM_DCL_PIN_MODE_EINT*/
#define VM_PIN_P1 3       /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_PWM */
#define VM_PIN_P2 27      /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_SPI */
#define VM_PIN_P3 28      /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_SPI */
#define VM_PIN_P4 29      /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_SPI */
#define VM_PIN_P5 19      /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_SPI */
#define VM_PIN_P6 43      /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_I2C */
#define VM_PIN_P7 44      /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_I2C */
#define VM_PIN_P8 10      /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_UART */
#define VM_PIN_P9 11      /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_UART */
#define VM_PIN_P10 57     /* Pin mux, VM_DCL_PIN_MODE_ADC */
#define VM_PIN_P11 0      /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_EINT / VM_DCL_PIN_MODE_ADC */
#define VM_PIN_P12 1      /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_EINT / VM_DCL_PIN_MODE_ADC */
#define VM_PIN_P13 2      /* Pin mux, VM_DCL_PIN_MODE_GPIO / VM_DCL_PIN_MODE_EINT / VM_DCL_PIN_MODE_ADC */
#define VM_PIN_P14 52     /* Pin mux, VM_DCL_PIN_MODE_EINT */
#else
#define VM_PIN_P0 0
#endif

#ifdef __cplusplus
}
#endif

#endif /* _VMBOARD_SDK_H */

